version: '3.8'

services:
  taxi-redis:
    container_name: taxi-redis
    image: redis:7-alpine

  taxi-server:
    container_name: taxi-server
    build:
      context: ./server
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - taxi-redis
    environment:
      - REDIS_URL=redis://taxi-redis:6379/0
    ports:
      - 8001:8000

  taxi-database:
    container_name: taxi-database
    environment:
      - POSTGRES_PASSWORD=taxi
    image: postgres:15-alpine
    ports:
      - 5433:5432
    volumes:
      - taxi-database:/var/lib/postgresql/data


volumes:
  taxi-database: