# Generated by Django 4.1.3 on 2023-04-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='Rid',
            new_name='id',
        ),
    ]
